Python Assignment - Geetha Kaliyappa

! pip install psycopg2-binary - Required installing of this Library for connecting with PostgreSQL Server

In [8]:
import pandas as pd
import numpy as np
import time
%matplotlib inline

import warnings
warnings.filterwarnings('ignore')

In [2]:
import psycopg2 as ps
conn = ps.connect(
    host="devtradingsagedb-do-user-12481132-0.b.db.ondigitalocean.com",
    port="25060",
    dbname="defaultdb",
    user="doadmin",
    password="AVNS_AZ-3Q1oUpp9WnsReBBX")

In [3]:
df = pd.read_sql_query("select * from test_assignment", con=conn)

In [4]:
df.head(5)

,date,ticker,strike,instrument_type,expiry_date,oi,underlying,last_update
0,2023-01-02,NIFTY23JAN14750CE,14750,CE,2023-01-25,5950,NIFTY,2023-01-02 10:30:11.098594+00:00
1,2023-01-02,NIFTY23JAN14750PE,14750,PE,2023-01-25,7850,NIFTY,2023-01-02 10:30:11.098594+00:00
2,2023-01-02,NIFTY23JAN14800CE,14800,CE,2023-01-25,0,NIFTY,2023-01-02 10:30:11.098594+00:00
3,2023-01-02,NIFTY23JAN14800PE,14800,PE,2023-01-25,0,NIFTY,2023-01-02 10:30:11.098594+00:00
4,2023-01-02,NIFTY23JAN14850CE,14850,CE,2023-01-25,0,NIFTY,2023-01-02 10:30:11.098594+00:00

<u>Step-by-step Algorithm:</u>

- So, the two dates will be entered by the user
- We need to see all the strikes for those two dates
- Then, get PE OI and CE OI for each strike
- Then, calculate the difference between respective PE OI and CE OI for each strike for that dates
- Then, convert the output to a DataFrame

So, on a given day, we have 121 Strikes for each CE and PE. among the Total count of 242 (121 * 2 = 242)

So for 2 given dates, we will get 121 differences of Open Interest for each CE and PE

In [20]:
def diff_cal(date1, date2):
    df1 = df[df['date'] == date1]
    df2 = df[df['date'] == date2] 
    
    strike_list1 = list(df1['strike'].unique())
    strike_list2 = list(df2['strike'].unique())
    
    if set(strike_list1) == set(strike_list2):
        print("We have same Strikes for" , date1 , "&" , date2)
        print("\nLoading...")
        CE1=[]
        PE1=[]
        CE2=[]
        PE2=[]
        for i in strike_list1:
            x1=int(df1[(df1['strike'] == i) & (df1['instrument_type'] == "CE")]['oi'])
            CE1.append(x1)
    
            y1=int(df1[(df1['strike'] == i) & (df1['instrument_type'] == "PE")]["oi"])
            PE1.append(y1)
    
            x2=int(df2[(df2['strike'] == i) & (df2['instrument_type'] == "CE")]['oi'])
            CE2.append(x2)
    
            y2=int(df2[(df2['strike'] == i) & (df2['instrument_type'] == "PE")]["oi"])
            PE2.append(y2)
            
        CE_Diff=[]                 #Calculating CE OI Difference and appending to the empty list CE_Diff
        for i,j in zip(CE1,CE2):
            CE_Diff.append(i-j)
        
        PE_Diff=[]                 #Calculating PE OI Difference and appending to the empty list PE_Diff
        for i,j in zip(PE1,PE2):
            PE_Diff.append(i-j)
        
        time.sleep(3)
            
        print("\nCE & PE OI Difference have been Obtained Successfully..!!! ")
        
        output=pd.DataFrame(strike_list1, columns = ['Strike']) #Creating a Dataframe with one columns
        output['CE OI Difference'] = CE_Diff                    #Adding another column to the above dataframe
        output['PE OI Difference'] = PE_Diff                    #Adding another column to the above dataframe
        pd.set_option('display.max_rows', None)                 #Displaying all rows in the dataframe
        return output                                           #returning the output dataframe to the user
    else:
        print("We don't have equal Strikes for date1 & date2") 
        print("Aborting Operation")

In [21]:
#Invoking the above created function

#User should enter Old Date followed by New Date in YYYY-MM-DD format.

#Example: diff_cal("YYYY-MM-DD", "YYYY-MM-DD")


Latest_Date="2023-01-02"
Prior_Date="2023-01-03"

diff_cal(Latest_Date,Prior_Date)

We have same Strikes for 2023-01-02 & 2023-01-03

Loading...

CE & PE OI Difference have been Obtained Successfully..!!!

     Strike  CE OI Difference  PE OI Difference
0     14750              -100             -1100
1     14800                 0                 0
2     14850                 0                 0
3     14900                 0                 0
4     14950                 0                 0
5     15000              4900              5200
6     15050                 0                 0
7     15100                 0                 0
8     15150                 0                 0
9     15200                 0                 0
10    15250                 0                 0
11    15300                 0                 0
12    15350                 0                 0
13    15400                 0                 0
14    15450                 0                 0
15    15500              -300               300
16    15550                 0                 0
17    15600                 0                50
18    15650                 0                 0
19    15700                 0                 0
20    15750                 0                 0
21    15800                 0             -1600
22    15850                 0                 0
23    15900                 0              1700
24    15950                 0                 0
25    16000              -450             -5600
26    16050                 0                 0
27    16100                 0             35550
28    16150                 0                 0
29    16200                 0             -1000
30    16250                 0                 0
31    16300                 0               550
32    16350                 0               400
33    16400                 0             -2050
34    16450                 0            -16850
35    16500              -900             46250
36    16550                 0              7050
37    16600              -100              4850
38    16650                 0                 0
39    16700               -50             29300
40    16750                 0              1350
41    16800               -50             60200
42    16850                 0             -5200
43    16900              -100            -50250
44    16950                 0              6450
45    17000              4500           -103250
46    17050               -50              2650
47    17100              -250             -5000
48    17150                 0             -3100
49    17200               350            107050
50    17250                 0            -12250
51    17300              -150              3200
52    17350              -100             -5700
53    17400               200              4450
54    17450                 0            -14700
55    17500             22000           -239600
56    17550              -200            -25600
57    17600               200            -41700
58    17650               150             -2500
59    17700               400            -62700
60    17750              -150            -23200
61    17800             -9800            -75350
62    17850               150            -12000
63    17900             -3700            -32900
64    17950               150             -9950
65    18000             90000           -156500
66    18050             -5300            -13450
67    18100             26450            -22750
68    18150            -11350             -7000
69    18200           -302500           -343650
70    18250            -24300            -16000
71    18300           -127000            -71100
72    18350             -6000             -2050
73    18400            -11900             -3050
74    18450              2650             -2050
75    18500           -181050            -36050
76    18550            -12750               -50
77    18600            -59900            -11000
78    18650             -7100             -1000
79    18700            -95700              4550
80    18750            -23850               -50
81    18800            -30900            -16650
82    18850              6350               100
83    18900            -48100              -250
84    18950             -9950              6500
85    19000           -125200              4200
86    19050             -7100                 0
87    19100             46300               650
88    19150               850                 0
89    19200           -150200               100
90    19250            -15050               -50
91    19300              3250               100
92    19350                 0                 0
93    19400             -9350               -50
94    19450                 0                 0
95    19500            -19850              3100
96    19550                 0                 0
97    19600             19000                 0
98    19650              -200                 0
99    19700              6350                 0
100   19750              -600                 0
101   19800             10150               -50
102   19850                 0                 0
103   19900               850                 0
104   19950              1550              -100
105   20000             41000              -700
106   20050              -350                 0
107   20100              3750              -200
108   20150              -150                 0
109   20200               400                 0
110   20250              -650                 0
111   20300              -350                 0
112   20350                50                 0
113   20400               400                 0
114   20450              -100                 0
115   20500             -5200             -2600
116   20550                 0                 0
117   20600               550                 0
118   20650              1000                 0
119   20700             -1050                50
120   20750             -3950              -250

# The End